version: "3"

services:
  test_mysql:
    image: mysql:$MYSQL_VERSION
    container_name: $MYSQL_NAME
    ports:
      - "${HOST_MYSQL_PORT}:3306"
    volumes:
      - ./db-backups:/var/mysql/backups
      - ./db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    restart: always
    command: "--default-authentication-plugin=mysql_native_password"
  test_site:
    build: . #thi is telling docker-composer to use Dockerfile from the main directory
    container_name: $WEB_NAME
    volumes:
      - ./docroot:/var/www/html
      - ./config:/home/config
    ports:
      - "${HOST_APACHE_PORT}:80"
volumes:
  db-data:
